### ISSUE TITLE
魔法哥的投票你来定

### ISSUE THREAD

**Issue by cssmagic** [cssmagic/DApp-VIP#4]
## 概述

群主（魔法哥）是星云激励计划的评审之一，拥有投票权。

最后一周的投票正在进行中。群主准备了 100 票，投给谁，由各位 VIP 群友（以下简称 “群友”）来定。

## 活动方式

1. 群友试用 [第八周的优秀应用](https://incentive.nebulas.io/cn/dapps-board.html)（:warning: 注意：仅限此页面前 23 名的优秀应用），选出自己最看好的 DApp。群友至少要有一笔和 DApp 合约的交易互动（请记录 txHash）。

1. 在本 issue 下留言，留下你的投票意向。 **每人可投两票**，每票的格式如下：

	> * 我的 VIP 编号： `1001`
	> * 我的星云昵称： `王大锤`
	> * 我的地址： `n1xxxxxxxxxxxxxxxx`
	> * 我与应用互动的 txHash： `xxxxxxxxxxxxxxxx`
	> * 我最看好的应用： `某某某`

1. 本周二（7 月 10 日）晚 10 点截止留言。

1. 群主根据群友的有效留言，统计出投票意向，把 100 票按比例投出。

1. 群主从意向最高的应用开始投票。如果在投票截止时 100 票仍未投完，将停止投票。

## 奖励方式

群友看好的应用如果最终获得了前三名，则可获得 NAS 奖励。举例来说：

* 小明看好的某款应用最终获得了冠军，他将获 1 NAS 奖励
* 小明看好的某款应用最终获得了亚军，他将获 0.5 NAS 奖励
* 小明看好的某款应用最终获得了季军，他将获 0.2 NAS 奖励

奖励将在星云官方公布评选结果后一周内发放。

***

<sup>* 本文档的最终解释权属于群主。</sup>

**Comment by cssmagic** [comment]
## 推荐应用

宣传图 | 宣传文稿
---|---
![webwxgetmsgimg](https://user-images.githubusercontent.com/1231359/42448416-a477be08-83af-11e8-9603-fb2df20f2e50.jpeg) | NAS星际穿越，6月21日封测至今，历时18天。有效注册人数866，均周活跃人数168，七日留存18.7%（S级），上链交易次数1200；<br><br>在全体星际穿越者努力下，一共发现8918未知星体，占领星体588颗。总航行里程109270光年；总消耗能量152978；总采集能量222100；第一星系发展进程15.52%<br><br>进程达到100%时，开启第二阶段。届时将组建第一界星际发展委员会，并逐步开放星球建设，飞船打造，交易所等功能。感谢所有《星际穿越》的玩家支持。<br><br>《星际穿越》的目标是成为最受欢迎的去中心化游戏。希望各位大大可以支持我们，感谢！<br><br>http://www.ospak.io

**Comment by liuqianghui** [comment]
我的 VIP 编号： 1021
我的星云昵称： liuqh
我的地址： n1Ee79mChdcHEUkbQoL1wensAXAKVYzkcsW
我与应用互动的 txHash：e463ab15ebb5a2d4ee2298581dcd0b25d0ba0e4bf632d37ce816b5891bbad64a
我最看好的应用： 模拟交易大赛

**Comment by crossingmay** [comment]
我的 VIP 编号： 1006
我的星云昵称： crossing
我的地址： n1ku6LvYBtYiqwi1Km4rKY7AmrRwuaAFNgd
我与应用互动的 txHash：9df4c69b347e69a592abde961aacaabf514010f5f08ba8308a6e3cea5ca2d9c4
我最看好的应用： 星际穿越

**Comment by cssmagic** [comment]
@crossingmay 
老兄，你留的地址和你登记的 VIP 地址不一致哦。

**Comment by xieqing0428** [comment]
我的 VIP 编号： 1016
我的星云昵称： 听泉
我的地址： n1HUHaFqmrJqPr6tRbmwfkKUD5qBy1KKFD3
我与应用互动的 txHash：0a6db3e53d4c4d6b0bd6a5c349826f7e23606a56265196226c3b227febc292ab
我最看好的应用： 天天免费领NAS

**Comment by lwzhang** [comment]
我的 VIP 编号： 1010
我的星云昵称： zhangliuwen
我的地址： n1ZEuuEXg9mn9yx99MQpNh1xb8eGwtrYzNN
我与应用互动的 txHash：ad4e07031d5cc0ef5a5ab07de301efa8bcbc59ddee333116c03cc8285c005c9a
我最看好的应用： 天天免费领NAS

**Comment by wuguoxu** [comment]
我的 VIP 编号： 1012
我的星云昵称： Guoxu
我的地址： n1LpoEpoYFgYtokji7yf3Fkm4HcbNxbYEWz
我与应用互动的 txHash：04e57132615b86675da1cd71212d0a94a9dbfa53c5e1303df24dddd33c91ef7e
我最看好的应用： 天天免费领NAS

**Comment by Harveytwo** [comment]
我的 VIP 编号： 1005
我的星云昵称： 斯密达
我的地址： n1TeKomxUFH7vcG22AreQTiswUPiKdMc5AF
我与应用互动的 txHash： 607e18bcd67819f0779ea35a4900498247bdb438e9d42d9dc0965927e4f82abd
我最看好的应用： Nebulas Mining

**Comment by Harveytwo** [comment]
我的 VIP 编号： 1005
我的星云昵称： 斯密达
我的地址： n1TeKomxUFH7vcG22AreQTiswUPiKdMc5AF
我与应用互动的 txHash： 07c8452d1a6e0afd0c693646a8ad615a698f714ba33089b08c9c47d156cf33c3
我最看好的应用： Nebulas Runner

**Comment by chengbotao** [comment]
我的 VIP 编号： 1013
我的星云昵称： ChengBoTao
我的地址： n1ZMaUo3dHzLtQBM4jrVNMbdbP2ije4ga7n
我与应用互动的 txHash： 79ed58072f49da2557b4ca2d94613a9ceef4773718751302680c21b465ee5f4c
我最看好的应用： 模拟交易大赛

**Comment by chenfaxiang** [comment]
我的 VIP 编号： 1014
我的星云昵称： chenfx
我的地址： n1LsrV1D8jGELfhwywY4qgiQZuDi9e1USvB
我与应用互动的 txHash： af455498b7cdb0d42cb5641c1956ada68ad76e4baf79a48a6ca6b88c6364f3d9
我最看好的应用： 模拟交易大赛

**Comment by woaichiji** [comment]
我的 VIP 编号： 1017
我的星云昵称： NONAME
我的地址： n1F8dyGVcx3B7krYfS5Zm2fSs8MHcPSBz6C
我与应用互动的 txHash： 21f5b4c67eaf961cd046df899194b936805e58fa65cfa211fed2c8c416ce0e6a
我最看好的应用： 模拟交易大赛

**Comment by DeanDai** [comment]
我的 VIP 编号： 1011
我的星云昵称： Dean
我的地址： n1T4JojigUfcnWzr7AEm2iYPQMubEnjydzn
我与应用互动的 txHash： 10fa84415782832074ab67dc7c187ffff8a8a133963e85f1278fd3e8fc6972b0
我最看好的应用： 天天领NAS

**Comment by EchoWht** [comment]
我的 VIP 编号： 1023
我的星云昵称： wanghaotian
我的地址： n1azHhZmq9enfcwikiLYuim4VmMm9aorRmi
我与应用互动的 txHash：0931072c86f9c369c890c66e321d2d93ddd098943e5ed2e07a14289e2aca61d0
我最看好的应用： 天天免费领NAS

**Comment by Harveytwo** [comment]
我的 VIP 编号： 1005
我的星云昵称： 斯密达
我的地址： n1TeKomxUFH7vcG22AreQTiswUPiKdMc5AF
我与应用互动的 txHash： 921567208c53d8be98587f7f1ff40bc6b982a38d9eaeecef1fc881a047200f57
我最看好的应用： Everyday NAS

**Comment by EchoWht** [comment]
我的 VIP 编号： 1023
我的星云昵称： wanghaotian
我的地址： n1azHhZmq9enfcwikiLYuim4VmMm9aorRmi
我与应用互动的 txHash：8165815c1a87d7265a5905d448c4f93dece22152667facabb4ab0c9a7821d293
我最看好的应用： 星云wiki

**Comment by DeanDai** [comment]
我的 VIP 编号： 1011
我的星云昵称： Dean
我的地址： n1T4JojigUfcnWzr7AEm2iYPQMubEnjydzn
我与应用互动的 txHash： 680d8f0fba8576b426699a7ff7bbdf6b63ae63c5404b230d94a153b0949fd151
我最看好的应用： NAS水龙头

**Comment by woaichiji** [comment]
我的 VIP 编号： 1017
我的星云昵称： NONAME
我的地址： n1F8dyGVcx3B7krYfS5Zm2fSs8MHcPSBz6C
我与应用互动的 txHash： e1273bc9f9d9f06be95d916169ed7b4e148d4b7d4283f1d3b4e2885ffd249d27
我最看好的应用： 星际穿越

**Comment by yujiayinshi** [comment]
我的 VIP 编号： 1025
我的星云昵称： yujiayinshi
我的地址： n1dDtZ6BdSLa3Auh7VN1LsNVU1ZCcfN9f2s
我与应用互动的 txHash：88f3ef6caa988f0a0383393773868ff01ea48c62c4101add320b40059676b554
我最看好的应用： 天天免费领NAS

**Comment by yujiayinshi** [comment]
我的 VIP 编号： 1025
我的星云昵称： yujiayinshi
我的地址： n1dDtZ6BdSLa3Auh7VN1LsNVU1ZCcfN9f2s
我与应用互动的 txHash：9ee19f86fca54aa029714f35f29b96a9b0e77d2d1c0ec4ed6b62a81dd8f30010
我最看好的应用： 模拟交易大赛

**Comment by yuzexia** [comment]
我的 VIP 编号： 1018
我的星云昵称： 不新鲜的萝卜皮
我的地址： n1PxSG2Wh6yPA4qHUQ24Lz38iPurniMBRgg
我与应用互动的 txHash：0a6db3e53d4c4d6b0bd6a5c349826f7e23606a56265196226c3b227febc292ab
我最看好的应用： 天天免费领NAS

**Comment by chengbotao** [comment]
我的 VIP 编号： 1013
我的星云昵称： ChengBoTao
我的地址： n1ZMaUo3dHzLtQBM4jrVNMbdbP2ije4ga7n
我与应用互动的 txHash： e60cee15e2c091e495f72382df6c1037dac84b1731f9a40ab9ee1b3914924051
我最看好的应用： 星图

**Comment by SniperQian** [comment]
我的 VIP 编号： 1027
我的星云昵称： SniperQian
我的地址： n1VutgC2MPJ79VqzF5JtouNjgQcpY5dwB4b
我与应用互动的 txHash： d48415772c3eff2b53eb0b79c1468a4a30a4ee687f0f90a8b73e4192e2b395cb
我最看好的应用： 天天领NAS

**Comment by vincent-zhu** [comment]
我的 VIP 编号： 1022
我的星云昵称： galois
我的地址： n1bmWAKgY995fb2jJLv9GmZsJABDUXVLtrQ
我与应用互动的 txHash： 0436f3f67212fafc7b7de74f987b8820dd7f3ca3df5f7ca49761ba12bfd55936
我最看好的应用： 天天领NAS

**Comment by newraina** [comment]
我的 VIP 编号： 1003
我的星云昵称： 吹风机漏气了
我的地址： n1JCrwtxFncexo87pLC4SSCqV7HZCnHoHJ2
我与应用互动的 txHash： f31d15ff91ef3efa86b21c5fce7dbd2111a3345c7d8a4f366e589a92313df348
我最看好的应用： 天天领NAS

**Comment by cssmagic** [comment]
群友投票结束～

**Comment by cssmagic** [comment]
投票汇总：

| 应用 | 群友票数 | 换算 NAS 票数
|:---:|---:|---:
模拟交易大赛 | 5 | 23
星际穿越 | 2 | 10
天天免费领NAS | 11 | 50
Nebulas Runner | 1 | 5
星云wiki | 1 | 5
NAS水龙头 | 1 | 5
星图 | 1 | 5
||
合计 | 22 | 103

**Comment by cssmagic** [comment]
“魔法哥的投票你来定” 活动收尾：

- 根据星云官方公告的周排名，没有群友选中前三名。
- 群主会向 22 位参与活动的群友空投 0.01 NAS（每人），聊表谢意 😉

**Comment by cssmagic** [comment]
“魔法哥的投票你来定” 活动奖金（每人 0.01 NAS）已全部发出，请查收～

奖金由合约批量发出。星云浏览器目前还看不到合约转来的款项，但你的余额是增加了的。
